permalink: /posts/:title/

paginate: 5
paginate_path: '/page/:num/'
excerpt_separator: '<!--more-->'
url: 'https://eddmann.com'

exclude: ['Gemfile', 'Gemfile.lock', 'vendor']

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-paginate
