name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Load Bundle Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ruby-2.7.2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ruby-2.7.2-

      - name: Build Jekyll Site
        run: make install build

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
